### PR TITLE
Prospector changes

### PR DESCRIPTION
**Pull request by costela**
This PR has two main changes:
- enabling merging of prospector info from multiple hiera levels (through `hiera_hash()`)
- adding a prospector_defaults field, that is used on `create_resource()`

and one minor fix: repo→key relationship on SLES

### CODE REVIEW

**Comment by pcfens** [comment]
Thanks for the PR. I'm going to cherry-pick the [bugfix](https://github.com/pcfens/puppet-filebeat/pull/25/commits/3ed95a154c120c259ee0cc20b7c70d15c9f2a9d4) so that it can get fixed while we figure out what to do with the rest of the changes.

I like the general idea, but I'm afraid this might be a breaking change. In the current implementation only the first hiera match of `filebeat::prospector` is used. If someone wants to implement the proposed behavior they could do something like
```puppet
class { 'filebeat':
  prospectors => hiera_hash('filebeat::prospector'),
}
```

In the proposed model, if `filebeat::prospector` is defined in hiera at various levels there isn't a way to only take the first match - this implementation makes the assumption that they should all be merged. The behavior of the defaults hash would also be impacted based on how [merging](https://docs.puppet.com/hiera/3.1/lookup_types.html#hash-merge) is configured.

Perhaps an additional parameter to enable this behavior would be better (and less breaking) than the [conditional approach](https://github.com/pcfens/puppet-filebeat/pull/25/files#diff-60ae41fd0a31977447947f59940ee9a4R65) proposed? Of course we'll need to get the tests passing before a merge too.

**Comment by costela** [comment]
Yes, you're absolutely right. To be honest I considered this problem for a while, and, without finding an easy solution, decided to create the PR first to get the ball rolling.

My initial idea was to provide a ```filebeat::prospectors_override``` argument, which would mimic the current behavior. But this obviously also be a breaking change.
If you're not against it, I'd suggest adding ```filebeat::prospectors_merged``` for the proposed behavior. This could then be mutually exclusive with ```filebeat::prospectors```, to avoid confusion.

As for the tests, we currently don't have Puppet 4.* in production, so this one slipped past my tests and might need a bit of experimentation.

PS.: if I don't manage to reimplement this tomorrow, I'll then be AFK for a couple of weeks. Just so you don't think this PR is a hit-and-run! ;)

**Comment by pcfens** [comment]
You've thought about this a lot more than I have, but figured I'd throw my first thoughts in - what about another boolean parameter like `filebeat::merge_prospectors` that changes the behavior to merge all of the `filebeat::prospector` entries?

There could be a default value in common.yaml (if the module default doesn't work out) that is overridden by more specific matches as needed.

**Comment by pcfens** [comment]
It looks like puppet 4 has a way to do this using [lookup_options](https://docs.puppet.com/puppet/latest/reference/lookup_quick.html#setting-lookupoptions-in-data) in hiera. Not sure if that changes anything, but figured it was worth mentioning here.

**Comment by costela** [comment]
That sounds more elegant. Just refactored the PR to include a boolean ```filebeat::prospectors_merge```, which when set makes the module use ```hiera_hash()```.

I also removed the proposed ```filebeat::prospector_defaults``` parameter in favour of using ```hiera()``` calls as the default for prospectors (since defines don't have automatic parameter lookup). This has the unfortunate side-effect of [ignoring "undef" defaults](https://projects.puppetlabs.com/issues/20923), so I had to hard-code defaults for ```filebeat::prospector::ignore_older``` and ```...::close_older```. Don't think that's a big issue, since all other parameters already have hard-coded defaults tracking filebeat's defaults, but let me know if I'm missing something.

**Comment by pcfens** [comment]
Would something like [resource defaults](https://docs.puppet.com/puppet/latest/reference/lang_defined_types.html#resource-defaults) work in place of hiera for the defined type? I've done some searching and can't find anything to support the (crazy?) idea that I somehow got in my head that hiera calls in modules are bad, though I can't find anything supporting hiera in modules either (with the exception [module data](https://docs.puppet.com/puppet/latest/reference/lookup_quick_module.html)).

Any thoughts?

**Comment by dMopp** [comment]
+1 for merge, hiera_hash is what iam currently looking for (filebeat::prospectors_merge)..

**Comment by pcfens** [comment]
I merged the commit related to calling `hiera_hash()` to create prospectors, and updated the [README](https://github.com/pcfens/puppet-filebeat#prospectors-in-hiera) and changelog files.

**Comment by costela** [comment]
@pcfens not sure what you mean with "resource defaults". This was the way it worked before my patch. But your message made me rethink my solution and I now believe it's actually unsuited for this sort of "sub-resource". The problem is the default values from hiera would take precedence over those provided via ```create_resources```. So they wouldn't be "defaults" as much as "overrides", kind of defeating the purpose ;). (I overlooked this because in my specific case I wasn't attempting to re-set the parameters via ```filebeat::prospectors```, so there was no overlap in parameters and everything seemed ok)

Would you be OK with the original idea of a ```prospector_defaults``` argument, which would then be passed as a third argument to ```create_resources```?

**Comment by pcfens** [comment]
Something like `prospector_defaults` sounds reasonable to me, though I think we should look at using the [resource defaults](https://docs.puppet.com/puppet/latest/reference/lang_defined_types.html#resource-defaults) so that the defaults will carry over to prospectors declared outside of hiera.

Resource defaults in this case might look like
```puppet
Filebeat::Prospector {
  param => value,
}
```

If defaults don't carry out of scope (I don't remember if they do or not) then a few notes in the documentation will probably suffice.

**Comment by costela** [comment]
So, sorry for disappearing there for a while... :)
I've taken a fresh look at the problem and I've come back to my ```hiera()``` proposal. My last argument against myself was just wrong (don't know where I got that idea). As the patch now stands, the precedence for parameters is this:

- parameters passed directly in the defined type instantiation (or the second argument of ```create_resources```, either via hiera or a manifest)
- parameters passed as third argument for ```create_resources```
- parameters passed via resource defaults (```Filebeat::Prospector {...}```)
- parameters passed via hiera ```filebeat::prospector::...```
- default parameters defined in the ```hiera()``` call in prospector.pp

This seems reasonable to me. Do you see any issue I might be overlooking?
I like this approach because it means you don't have to look up some extra parameter in order to set defaults, and the approach is similar whether you're using hiera or not (```Filebeat::Prospector {...}``` in a manifest is more similar to ```filebeat::prospector::...``` in hiera than to an extra ```filebeat::prospector_defaults``` parameter, right?)

As to the reluctance to use ```hiera()``` as default, I also couldn't find any mention of it causing problems. On the contrary, I could find a couple of instances of people suggesting it as a reasonable solution ([here](https://ask.puppet.com/question/15094/can-you-use-automatic-parameter-lookup-with-defined-types/) and [here](https://ask.puppet.com/question/2077/how-are-people-using-hiera-with-defined-types/)).

**Comment by pcfens** [comment]
I'm afraid I'm still a little fuzzy on whether or not hiera calls in modules at all is a good idea. While being a Puppet approved module isn't a set goal, I look at the [requirements](https://forge.puppet.com/approved/criteria) as a guide to a high quality module. They suggest (at the very bottom) that modules shouldn't call out to hiera, but don't offer alternatives in the case of defined types.

I think the community concern about using hiera() in modules is that a lot of avoidable assumptions have to be made about an environment.

Just to make sure I understand all of this (it's been a while)- what's the use case where resource defaults won't work?

**Comment by pcfens** [comment]
I'm going to go ahead and close this since hiera 5 changes how a lot of this works and is calls to `hiera_*()` are being deprecated. If you think the module is still lacking something feel free to send a PR or open an issue.

**Pull request closed without merging**
