### PR TITLE
Update apt dependency

### PR DESCRIPTION
**Pull request by cdenneen**
Apt dependency updated to <5.0.0

### CODE REVIEW

**Comment by pcfens** [comment]
Thanks - I'm going to push out version 2.0 sometime this week and will include this in it.

**Comment by cdenneen** [comment]
Thanks. Curious the `processors` feature says it's only supported by Filebeat 5 and in upcoming release you'll only support >=5 so why would processors become deprecated in upcoming release? I haven't fully read it but except for the `versioncmp` for `<5` shouldn't it still be valid?

**Comment by pcfens** [comment]
I may need to clarify the wording some - Filebeat processors will still work, but not the puppet resource `filebeat::processor` (they're replaced by a `processors` parameter on the filebeat class).

**Comment by cdenneen** [comment]
Great thanks!

**Pull request merged**
