### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by axier**
I want to add windows support to your module. This module is tested on windows 2012 R2 servers.

### CODE REVIEW

**Comment by pcfens** [comment]
This is awesome! Thanks so much for adding windows support - since I'm not a windows user, I probably never would have done this.

Can you make the download URL a parameter so it can be modified for systems that aren't connected to the internet? Does downloading the zip file with [`lwf/remote_file`](https://forge.puppetlabs.com/lwf/remote_file) work in place of powershell? If we're able to use something that isn't OS specific then it'll be easier to add non-package install support for Linux, though we'll probably need another class like `filebeat::download`. `install_dir`, and `tmp_dir` should probably be made parameters too so that everything is covered too.

Does it make sense to rename filebeat::install to something like filebeat::install::windows, just to keep things separated, as well as give us a spot to add a similar installer for Linux?

**Comment by pcfens** [comment]
I've merged this into a new branch, [windows](https://github.com/pcfens/puppet-filebeat/tree/windows), as a working place while some of the few outstanding issues are handled before merging into master.

**Comment by pcfens** [comment]
I've done some pretty heavy re-factoring to set things up in case we ever need to add the ability to download and install from tarball on Linux. I also replaced the powershell download with [lwf/remote_file](https://forge.puppetlabs.com/lwf/remote_file).

Tests seem happy so far, but since I'm not a windows person I'd appreciate it if someone could test the latest branch before I look at merging it in.

**Comment by pcfens** [comment]
Hi @axier - I made a few tweaks after my own testing, and now things seem to work without any problems in a vagrant 2012R2 box.

**Comment by axier** [comment]
Sorry for the late response but I have been a little busy those days. I see that you have done lot of improvements. I will test the windows branch. Let me know if I can help in something.

**Comment by pcfens** [comment]
Sorry if it felt like I was bugging you - I just wanted to make sure I documented what was going on a bit so it'd be easy to catch up. This will be an awesome addition. Thanks again for all your help.

**Pull request merged**
