### PR TITLE
Add support for Filebeat 6

### PR DESCRIPTION
**Pull request by joshuaspence**
Adds a `$major_version` parameter so that Filebeat 6 can be installed.

### CODE REVIEW

**Comment by pcfens** [comment]
Thanks! If you have time, can you update the README file to with a note about how to upgrade and add the `major_version` parameter too?

If you won't have time I'll merge this when I'll be at a computer long enough to add it (probably tomorrow morning eastern US time).

Thanks again!

**Comment by joshuaspence** [comment]
Yeah, can do. I just realized I need to tweak some more things anyway

**Comment by joshuaspence** [comment]
Oops, clicked the wrong button.

**Comment by joshuaspence** [comment]
Hm, the Travis failure seems unrelated.

**Comment by pcfens** [comment]
Yeah - I'll have to look at those particular tests a little later. I'll try to get this merged in the morning. Thanks again for adding support for v6.

**Pull request merged**
