### PR TITLE
Allow for nested fields

### PR DESCRIPTION
**Pull request by kimor79**

### CODE REVIEW

**Comment by pcfens** [comment]
Thanks for adding this functionality. Unfortunately, using the `to_yaml` method has caused some weird results with indenting int he past. One attempted fix was reverted in #81, but eventually we moved processors out to avoid the issue all together.

Dropping support for puppet 3 would solve some of the problems (though maybe then the entire configuration file could be generated with `to_yaml()` like I originally tried to do).

I'm not going to close this, but unfortunately I also can't merge it without breaking some things right now that I'm not quite ready to break.

**Comment by pcfens** [comment]
Can you take a look to see if this will be fixed by the default generic template in the [remove_old_version_support](https://github.com/pcfens/puppet-filebeat/tree/remove_old_version_support) branch? I suspect that it will work, but don't want to close this until I know for sure. Thanks!

**Comment by kimor79** [comment]
Thanks. I'll give it a try

**Comment by kimor79** [comment]
Seems to work. Thanks!

**Pull request closed without merging**
