### PR TITLE
Fix error when max_procs is empty

### PR DESCRIPTION
**Pull request by elconas**
Fix an error when max_procs beeing undef leading to: 

```
### Filebeat configuration managed by Puppet ###
---
...
  max_procs: !ruby/sym undef
```

### CODE REVIEW

**Comment by pcfens** [comment]
Thanks. I'm traveling today but will try to get a release on the forge tonight or tomorrow morning.

**Comment by elconas** [comment]
Great. Thanks. Fasted merge ever !

**Comment by elconas** [comment]
When do you plan to release ?

**Comment by pcfens** [comment]
I just pushed it up as v0.8.7.

Took a little bit longer since I'm at USENIX LISA this week :smile:

**Pull request merged**
