### PR TITLE
I had a few errors I corrected. duplicate entries and bad indentation

### PR DESCRIPTION
**Pull request by csoleimani**

### CODE REVIEW

**Comment by pcfens** [comment]
It looks like some of this stuff may have already found it's way in. Can you take a look at the [current version](https://github.com/pcfens/puppet-filebeat/blob/master/templates/filebeat5.yml.erb#L223-L234) to see if it will work?

**Comment by csoleimani** [comment]
That was from me, but the indentation is bad and I put ssl certificate and key in twice instead of just once. Also, ssl_key attribute says ssl.certificate. This should fix that

**Comment by pcfens** [comment]
Oops - I was reading too fast.

Could you try rebasing and fixing the merge conflict? Once that's done it should be easy for me to merge this (and I'll roll a new release afterwards).

**Comment by csoleimani** [comment]
whoops, sorry I think I merged it, but I fixed the conflict

**Pull request merged**
