### PR TITLE
Add support for filebeat v5

### PR DESCRIPTION
**Pull request by kimor79**
I haven't tested with current version of filebeat (1.2) as I need v5

### CODE REVIEW

**Comment by pcfens** [comment]
Thanks for this.

Since filebeat v5 is still in alpha, I'm a little hesitant to merge this quite yet, but this is probably a good place to start working on v5 support.

Before merging this we'll need to add some spec and acceptance tests too.

**Comment by joshuaspence** [comment]
It looks like Filebeat v5 has been released now. Any chance of this being merged? It looks like it still needs tests.

**Comment by rvdh** [comment]
+1 for v5 support!

**Comment by corey-hammerton** [comment]
+1 too. However the repository URLs for v5 have changed from 1.x. See https://www.elastic.co/guide/en/beats/libbeat/5.0/setup-repositories.html

**Comment by pcfens** [comment]
I'm going to close this since it needs a lot of work that I've done over in the [filebeat5](https://github.com/pcfens/puppet-filebeat/tree/filebeat5) branch.

I'll update bits and pieces (and look for some testers) over in the discussion for #44.

**Pull request closed without merging**
