### PR TITLE
Allow processors to be applied to all inputs, and consolidated common configuration

### PR DESCRIPTION
**Pull request by jbehrends**
* Moved processors outside of the main if/else so they can be used for ALL inputs
* Consolidated all "common configurations" which can be applied to all inputs together.

### CODE REVIEW

**Comment by pcfens** [comment]
Thanks!  Before I cut a release on this I just wanted to confirm that it doesn't risk breaking any existing configs by moving this part around (we don't use processors, so I wanted to be sure).

**Comment by jbehrends** [comment]
Sure thing! The logic of IF the processor is even defined is still the same.  It's just no longer gated inside the "if @input_type" statement.

**Comment by jbehrends** [comment]
@pcfens  Wanted to ping you about the possibility of cutting a release with this change in it.

**Comment by pcfens** [comment]
I just pushed this as 4.6.0

**Pull request merged**
